backend:
  name: git-gateway                  # Backend set to GitHub
  repo: ficklesheep/hugobegg     # Your GitHub repository name
  branch: dev                   # The branch to deploy (usually 'main' or 'master')

media_folder: "static/bloguploads"   # Folder where media files will be uploaded
public_folder: "/bloguploads"        # Public URL to access uploaded media files

media_library:
  name: local                    # Using the local media library
  config:
    media_folder: "static/bloguploads"  # Same folder for media files
    public_folder: "/bloguploads"      # Public URL path for accessing medipa files

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    nested:
      depth: 2                  # 👈 Tells Netlify CMS to look in subfolders (e.g., 2025/07/)
    slug: "{{year}}/{{month}}/{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

