backend:
  name: git-gateway
  repo: ficklesheep/hugobegg
  branch: dev

media_folder: "static/bloguploads"
public_folder: "/bloguploads"

media_library:
  name: local
  config:
    media_folder: "static/bloguploads"
    public_folder: "/bloguploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    nested:
      depth: 2
    slug: "{{year}}/{{month}}/{{day}}-{{slug}}"
    extension: "md"           # Ensure CMS only reads .md files
    format: "frontmatter"     # Use frontmatter format
    filter:                  # Ensure only posts with date are shown (optional)
      pattern: "*.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
