backend:
  name: git-gateway                  # Backend set to GitHub
  repo: ficklesheep/hugobegg     # Your GitHub repository name
  branch: master                   # The branch to deploy (usually 'main' or 'master')

media_folder: "static/bloguploads"   # Folder where media files will be uploaded
public_folder: "/bloguploads"        # Public URL to access uploaded media files

media_library:
  name: local                    # Using the local media library
  config:
    media_folder: "static/bloguploads"  # Same folder for media files
    public_folder: "/bloguploads"      # Public URL path for accessing medipa files

collections:
  - name: "blog"                 # The name of the collection (e.g., 'blog')
    label: "Blog Posts"           # Label for the collection
    folder: "content/blog"        # Folder where blog posts will be stored (relative to project root)
    create: true                  # Allows users to create new blog posts
    slug: "{{year}}/{{month}}/{{day}}-{{slug}}"  # URL format for blog posts
    fields:
      - { label: "Title", name: "title", widget: "string" }  # Field for blog title
      - { label: "Body", name: "body", widget: "text" }      # Field for blog body
