backend:
  name: git-gateway
  branch: dev
  repo: ficklesheep/hugobegg

media_folder: "static/bloguploads"
public_folder: "/bloguploads"

collections:
  - name: blog
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    format: frontmatter
    extension: md
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Simplified slug for testing
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
