backend:
  name: git-gateway
  repo: ficklesheep/hugobegg
  branch: dev

media_folder: "static/bloguploads"
public_folder: "/static/bloguploads"

media_library:
  name: local
  config:
    media_folder: "static/bloguploads"
    public_folder: "/static/bloguploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog" 
    create: true
    slug: "{{slug}}"  # Keep files flat in content/blog
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "" }
      - { label: "Image", name: "image", widget: "image" }  # ✅ New image field
      - { label: "Body", name: "body", widget: "text" }
